'use strict';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CURRENT_EVENT_ATTENDANCE_RECEIVED = 'CURRENT_EVENT_ATTENDANCE_RECEIVED';
export const ATTENDANCE_CHANGED = 'ATTENDANCE_CHANGED';
