'use strict';

export const FB_COLLECTION_RECEIVED = 'FB_COLLECTION_RECEIVED';
export const FB_CLEAR_COLLECTION = 'FB_CLEAR_COLLECTION';
export const FB_CHILD_CHANGED = 'FB_CHILD_CHANGED';
export const FB_CHILD_ADDED = 'FB_CHILD_ADDED';
export const FB_CHILD_REMOVED = 'FB_CHILD_REMOVED';
